// Code generated by ent, DO NOT EDIT.

package ent

import (
	"line-bot-app/ent/category"
	"line-bot-app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCategoryId is the schema descriptor for categoryId field.
	categoryDescCategoryId := categoryFields[0].Descriptor()
	// category.DefaultCategoryId holds the default value on creation for the categoryId field.
	category.DefaultCategoryId = categoryDescCategoryId.Default.(string)
	// categoryDescCategoryName is the schema descriptor for categoryName field.
	categoryDescCategoryName := categoryFields[1].Descriptor()
	// category.DefaultCategoryName holds the default value on creation for the categoryName field.
	category.DefaultCategoryName = categoryDescCategoryName.Default.(string)
	// categoryDescCategoryUrl is the schema descriptor for categoryUrl field.
	categoryDescCategoryUrl := categoryFields[2].Descriptor()
	// category.DefaultCategoryUrl holds the default value on creation for the categoryUrl field.
	category.DefaultCategoryUrl = categoryDescCategoryUrl.Default.(string)
}
